author: "ItzDabbzz"
branding:
  color: "yellow"
  icon: "star"
description: "Collection of widgets for your profile README updated and extended with love"
inputs:
  feed:
    description: "Path to FEEDS.json input file"
    required: false
  github_token:
    description: "GitHub token used for API requests"
    required: true
  readme:
    default: "./README.md"
    description: "README.md output file path"
    required: false
  template:
    default: "./TEMPLATE.md"
    description: "TEMPLATE.md file path"
    required: false
  username:
    description: "GitHub profile username"
    required: true
  wakatime_key:
    description: "WakaTime API key"
    required: false
name: "Profile Readme Widgets"
runs:
  main: "dist/index.js"
  using: "node24"
