author: "ItzDabbzz"
branding:
  color: "yellow"
  icon: "star"
description: "Collection of widgets for your profile README updated and extended with love"
inputs:
  feed:
    description: "FEED.json file path"
    required: false
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  readme:
    default: "./README.md"
    description: "README.md output file path"
    required: true
  template:
    default: "./TEMPLATE.md"
    description: "TEMPLATE.md file path"
    required: true
  username:
    description: "Github profile username"
    required: true
  wakatime_key:
    description: "WakaTime API Key"
    required: false
name: "Profile Readme Widgets"
runs:
  main: "dist/index.js"
  using: 'node24'
